version: '3.5'

services:
  backend:
    image: mbool/limbo_backend:latest
    container_name: limbo-backend
    ports:
      - 80:3005
    restart: always
  emqx:
    image: emqx/emqx:latest
    container_name: emqx-broker
    ports:
      - 18083:18083
      - 8083:8083
    restart: always
